version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_checkout:
    - git fetch --unshallow
conda:
  environment: docs/website/requirements.yaml
python:
  install:
  - method: pip
    path: .
sphinx:
  configuration: docs/website/source/conf.py
  builder: dirhtml
  fail_on_warning: false
formats: all
