version: 2
formats: all
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_checkout:
      - git fetch --unshallow
conda:
  environment: .devcontainer/container-docs/environment/conda/website.yaml
python:
  install:
    - method: pip
      path: pkg
sphinx:
  configuration: docs/website/source/conf.py
  builder: dirhtml
  fail_on_warning: false
