FROM mcr.microsoft.com/devcontainers/universal:2-linux
COPY .devcontainer/environment /usr/local/share/environments/
COPY .devcontainer/install.py /usr/local/share/app_installation/install.py
COPY .github/.repodynamics/metadata.json /usr/local/share/app_installation/metadata.json
