name: Install Environment
description: |
  Replicate a devcontainer environment for the repository.
inputs:
  devcontainer_keys:
    description: |
      Comma-separated list of devcontainer IDs to replicate.
      If not provided, all devcontainers are included.
    required: false
    default: ""
  load_cache:
    description: Load the local cache directory for the branch.
    required: false
    default: 'true'
  activate_env:
    description: Name of a Conda environment to activate on all shells.
    required: false
    default: base
  repo_path:
    description: Path to the root of the repository.
    required: false
    default: .
outputs:
  temp_dirpath:
    value: ${{ steps.script.outputs.temp_dirpath }}
    description: Path to the temporary directory in the branch.
  report_dirpath:
    value: ${{ steps.script.outputs.report_dirpath }}
    description: Path to the report directory in the branch.
runs:
  using: composite
  steps:
    - name: Action Path
      id: path
      shell: bash
      run: |
        # Get the absolute path to the action directory.
        echo "action_path=$(realpath --no-symlinks "${{ github.action_path }}")" >> "$GITHUB_OUTPUT"
    - name: Python Setup
      # https://github.com/actions/setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '>=3.10'
        check-latest: 'true'
        cache: pip
        cache-dependency-path: ${{ steps.path.outputs.action_path }}/requirements.txt
    - name: Environment Setup
      shell: bash
      run: |
        # Install action requirements
        echo "::group::pip install"
        python -m pip install -r "${{ steps.path.outputs.action_path }}/requirements.txt"
        echo "::endgroup::"
        echo "::group::pip list"
        pip list
        echo "::endgroup::"
    - name: Metadata Processing
      id: script
      shell: bash
      env:
        ACTION_INPUTS: ${{ toJSON(inputs) }}
      run: |
        # Process metadata.
        python "${{ github.action_path }}/script.py"
    - name: Cache Load
      if: inputs.load_cache == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ steps.script.outputs.cache_dirpath }}
        key: >-
          local--${{ runner.os }}--${{ runner.arch }}--${{ github.repository }}/${{ steps.script.outputs.branch_name }}
    - name: Bash Install
      if: steps.script.outputs.bash_filepaths
      env:
        BASH_FILEPATHS: ${{ steps.script.outputs.bash_filepaths }}
      shell: bash
      run: |
        # Install packages from bash scripts.
        while IFS= read -r bash_filepath; do
          echo "::group::bash ${bash_filepath}"
          bash "$bash_filepath"
          echo "::endgroup::"
        done <<< "$BASH_FILEPATHS"
    - name: APT Install
      # TODO: add caching
      # - https://github.com/awalsh128/cache-apt-pkgs-action
      # - https://stackoverflow.com/questions/59269850/caching-apt-packages-in-github-actions-workflow/60920684#60920684
      if: runner.os == 'Linux' && steps.script.outputs.apt_filepaths
      env:
        APT_FILEPATHS: ${{ steps.script.outputs.apt_filepaths }}
      shell: bash
      run: |
        # Install APT packages
        echo "::group::apt-get update"
        sudo apt-get update
        echo ::endgroup::
        packages=$(cat $APT_FILEPATHS | xargs -d '\n' echo | tr '\n' ' ')
        echo "::group::apt-get install"
        sudo apt-get -y install --no-install-recommends $packages
        echo ::endgroup::
    - name: Conda Setup
      # https://github.com/conda-incubator/setup-miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        channels: conda-forge
        conda-remove-defaults: true
        auto-update-conda: true
        conda-build-version: '>=25.1.2'
        activate-environment: >-
          ${{ (inputs.activate_env != 'base' && inputs.activate_env) || '' }}
        auto-activate-base: ${{ steps.script.outputs.activate_env == 'base' }}
    - name: Conda Cache
      id: conda-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.CONDA }}/envs
        key: >-
          conda--${{ runner.os }}--${{ runner.arch }}--${{ steps.script.outputs.env_hash }}
    - name: Conda Install
      if: steps.conda-cache.outputs.cache-hit != 'true'
      shell: bash
      env:
        ENV_FILEPATHS: ${{ steps.script.outputs.env_filepaths }}
      run: |
        # Install Conda environments.
        while IFS= read -r env_filepath; do
          echo "::group::conda env update $env_filepath"
          conda env update -vv --file "$env_filepath"
          echo "::endgroup::"
        done <<< "$ENV_FILEPATHS"
    - name: Internal Package Install
      shell: bash -el {0}
      env:
        POST_COMMANDS: ${{ steps.script.outputs.post_commands }}
      run: |
        # Install internal packages.
        while IFS= read -r post_command; do
          echo "::group::$post_command"
          eval "$post_command"
          echo "::endgroup::"
        done <<< "$POST_COMMANDS"
    - name: Conda Info
      shell: bash -el {0}
      env:
        ENV_NAMES: ${{ steps.script.outputs.env_names }}
      run: |
        echo "::group::conda info"
        conda info
        echo "::endgroup::"
        echo "::group::conda config"
        conda config --show
        echo "::endgroup::"
        echo "::group::conda env list"
        conda env list
        echo "::endgroup::"
        while IFS= read -r env_name; do
          echo "::group::conda list $env_name"
          conda list --name "$env_name"
          echo "::endgroup::"
        done <<< "$ENV_NAMES"
    - name: Task Sourcing
      if: steps.script.outputs.task_filepaths
      shell: bash
      env:
        TASK_FILEPATHS: ${{ steps.script.outputs.task_filepaths }}
      # Setup-miniconda removes ~/.bashrc and ~/.bash_profile
      # and instead adds ~/.profile, which is sourced on all shells.
      # - https://github.com/conda-incubator/setup-miniconda/issues/151
      # - https://github.com/conda-incubator/setup-miniconda/issues/172
      run: |
        # Source task scripts.
        while IFS= read -r task_filepath; do
          printf '\nsource "%s"\n' "$task_filepath" | tee -a ~/.profile
        done <<< "$TASK_FILEPATHS"
