root: index
defaults:
  hidden: true
entries:
  - file: intro/index
    title: Intro
    options:
      numbered: true
    entries:
      - file: intro/motivation/index
      - file: intro/overview/index
      - file: intro/background/index
        entries:
          - file: intro/background/methodologies/index
          - file: intro/background/github/index
          - file: intro/background/python/index
            entries:
              - file: intro/background/python/pypi/index
              - file: intro/background/python/pip/index
              - file: intro/background/python/packaging/index
              - file: intro/background/python/governance/index
          - file: intro/background/conda/index
            entries:
              - file: intro/background/conda/packaging/index
          - file: intro/background/versioning/index
          - file: intro/background/jsonpath/index
          - file: intro/background/yaml/index
          - file: intro/background/toml/index
          - file: intro/background/jinja/index
          - file: intro/background/markdown/index
      - file: intro/glossary/index
      - file: intro/references/index
  - file: manual/index
    title: Manual
    options:
      numbered: true
    entries:
      - file: manual/install/index
        entries:
          - file: manual/install/new/index
          - file: manual/install/existing/index
          - file: manual/install/upgrade/index
          - file: manual/install/common/index
      - file: manual/quickstart/index
      - file: manual/config/index
        entries:
          - file: manual/config/location/index
          - file: manual/config/structure/index
          - file: manual/config/options/index
          - file: manual/config/synchronization/index
          - file: manual/config/outputs/index
          - file: manual/config/templating/index
          - file: manual/config/inheritance/index
          - file: manual/config/hooks/index
          - file: manual/config/caching/index
  - file: api/index
    title: API
    entries:
      - file: api/metadata/index
      - file: api/local/index
      - file: api/changelog/index
      - file: api/variables/index
      - file: api/contributors/index
      - file: api/cache/index
      - file: api/refs/index
  - file: news/index
    title: News
    entries:
      - glob: news/post/**
  - file: contribute/index
    title: Contribute
    options:
      numbered: true
    entries:
      - file: contribute/feedback/index
        entries:
          - file: contribute/feedback/security/index
          - file: contribute/feedback/bug/index
      - file: contribute/develop/index
      - file: contribute/support/index
  - file: about/index
    title: About
    options:
      numbered: true
    entries:
      - file: about/citation/index
      - file: about/contact/index
      - file: about/license/index
        entries:
          - glob: about/license/*/index
  - file: help/index
    title: Help
    options:
      numbered: true
    entries:
      - file: help/website/index
        entries:
          - file: help/website/tips/index
          - file: help/website/api/index
