name: '[Reusable]: Website'
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: QEMU Setup
        uses: docker/setup-qemu-action@v3
      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.16.1
          platforms: linux/amd64,linux/arm64
          install: true
          use: true
      - name: GitHub Container Registry Login
        # https://github.com/docker/login-action
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/repodynamics/devcontainer-docs
          configFile: .devcontainer/container-docs/devcontainer.json
          cacheFrom: ghcr.io/repodynamics/devcontainer-docs
          runCmd: sleep 1
          push: always
          cacheTo: type=registry,ref=ghcr.io/repodynamics/devcontainer-docs:latest
          platform: linux/amd64,linux/arm64
