# Install package from a given source and run unit-tests.
# Install the package and run tests on a matrix of supported Python versions and operating systems.

name: '[Reusable]: Package - Test'

on:
  workflow_call:
    inputs:
      config:
        type: string
        required: true
        description: Configuration as a JSON string.

jobs:
  test:
    name: ${{ matrix.task.name }}
    permissions:
      id-token: write  # For token-less upload of coverage reports to Codecov.
    strategy:
      fail-fast: false
      matrix:
        task: ${{ fromJSON(inputs.config).tasks }}
    runs-on: ${{ matrix.task.runner }}
    steps:
      - name: Repository Checkout
        if: (fromJSON(inputs.config).test-src != 'pypi') || (fromJSON(inputs.config).pkg-src != 'pypi')
        uses: actions/checkout@v4  # https://github.com/actions/checkout
        with:
          repository: ${{ fromJSON(inputs.config).repository }}
          ref: ${{ fromJSON(inputs.config).ref }}
          fetch-tags: true
          path: repo
      - uses: RepoDynamics/PyTester@v1
        with:
          python-version: ${{ matrix.task.python }}
          test-src: ${{ fromJSON(inputs.config).test-src }}
          test-path: ${{ fromJSON(inputs.config).test-path }}
          test-name: ${{ fromJSON(inputs.config).test-name }}
          test-version: ${{ fromJSON(inputs.config).test-version }}
          test-req-path: ${{ fromJSON(inputs.config).test-req-path }}
          pkg-src: ${{ fromJSON(inputs.config).pkg-src }}
          pkg-path: ${{ fromJSON(inputs.config).pkg-path }}
          pkg-name: ${{ fromJSON(inputs.config).pkg-name }}
          pkg-version: ${{ fromJSON(inputs.config).pkg-version }}
          pkg-req-path: ${{ fromJSON(inputs.config).pkg-req-path }}
          retries: ${{ fromJSON(inputs.config).retries }}
          retry-sleep-seconds: ${{ fromJSON(inputs.config).retry-sleep-seconds }}
          pyargs: ${{ fromJSON(inputs.config).pyargs }}
          args: ${{ fromJSON(inputs.config).args }}
          overrides: ${{ fromJSON(inputs.config).overrides }}
      - name: uname
        run: uname -a
      - name: Report Upload
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.task.artifact.report.name }}
          path: report
      - name: CodeCov Upload
        if: ${{ !cancelled() && fromJSON(inputs.config).upload-codecov }}
        # https://github.com/marketplace/actions/codecov
        # https://github.com/codecov/codecov-action
        env:
          OS: ${{ runner.os }}
          PYTHON: ${{ matrix.task.python }}
        uses: codecov/codecov-action@v4
        with:
          # TODO: Check that env_vars are correctly set. (https://github.com/codecov/codecov-action/pull/64)
          codecov_yml_path: repo/${{ fromJSON(inputs.config).codecov-yml-path }}
          directory: report
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          root_dir: repo
          use_oidc: true  # https://github.com/codecov/codecov-action/issues/1489#issuecomment-2197308411
          verbose: true
  report:
    name: Report
    if: ${{ !cancelled() && fromJSON(inputs.config).artifact.report.merge }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Artifact Merge
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ fromJSON(inputs.config).artifact.report.merge.name }}
          pattern: ${{ fromJSON(inputs.config).artifact.report.merge.pattern }}
          include-hidden-files: ${{ fromJSON(inputs.config).artifact.report.include-hidden }}
          retention-days: ${{ fromJSON(inputs.config).artifact.report.retention-days }}
          separate-directories: 'true'
          delete-merged: 'true'
