name: '[Reusable]: Website'
on:
  workflow_call:
    inputs:
      config:
        type: string
        required: true
        description: Configuration as a JSON string.
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
      - name: Repository Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ fromJSON(inputs.config).repository }}
          ref: ${{ fromJSON(inputs.config).ref }}
          fetch-depth: 0
      - name: GitHub Container Registry Login
        # https://github.com/docker/login-action
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      # TODO: Build for multiple platforms:
      # - https://github.com/devcontainers/ci/issues/299#issuecomment-2694214792
      # - https://github.com/actions/runner-images/issues/2875
      - name: Build
        # https://github.com/devcontainers/ci
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6  # https://github.com/devcontainers/ci/releases/tag/v0.3.1900000417
        env: ${{ fromJSON(inputs.config).container.env }}
        with:
          configFile: ${{ fromJSON(inputs.config).container.path }}
          imageName: ghcr.io/${{ fromJSON(inputs.config).container.name }}
          cacheFrom: ghcr.io/${{ fromJSON(inputs.config).container.name }}
          runCmd: ${{ fromJSON(inputs.config).container.command }}
          refFilterForPush: ${{ fromJSON(inputs.config).container.ref }}
          env: ${{ fromJSON(inputs.config).container.env-names }}
          inheritEnv: ${{ toJSON(fromJSON(inputs.config).container.inherit-env) }}
          push: filter
      - name: Build Preview
        if: ${{ !cancelled() }}
        run: find ${{ fromJSON(inputs.config).artifact.build.path }}
      - name: Build Artifact Upload
        if: ${{ !cancelled() }}
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ fromJSON(inputs.config).artifact.build.name }}
          retention-days: ${{ fromJSON(inputs.config).artifact.build.retention_days }}
          include-hidden-files: ${{ fromJSON(inputs.config).artifact.build.include_hidden }}
          path: ${{ fromJSON(inputs.config).artifact.build.path }}
      - name: GH-Pages Artifact Upload
        if: ${{ !cancelled() && fromJSON(inputs.config).deploy }}
        id: upload-pages
        # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ fromJSON(inputs.config).artifact.pages.name }}
          retention-days: ${{ fromJSON(inputs.config).artifact.pages.retention_days }}
          path: ${{ fromJSON(inputs.config).artifact.pages.path }}
  deploy:
    name: Deploy
    if: fromJSON(inputs.config).deploy
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: ${{ fromJSON(inputs.config).env.name }}
      url: ${{ fromJSON(inputs.config).env.url }}
    runs-on: ubuntu-latest
    steps:
      - name: GH-Pages Configuration
        id: configure-pages
        # https://github.com/actions/configure-pages
        uses: actions/configure-pages@v5
      - name: GH-Pages Deployment
        id: deploy
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ fromJSON(inputs.config).artifact.pages.name }}
